
CREATE TABLE assessors_2024_geo (
	object_id BIGINT, 
	parcel_number TEXT, 
	ward TEXT, 
	address TEXT, 
	council_district TEXT, 
	zip_code TEXT, 
	taxpayer_1 TEXT, 
	taxpayer_2 TEXT, 
	taxpayer_street TEXT, 
	taxpayer_city TEXT, 
	taxpayer_state TEXT, 
	taxpayer_zip TEXT, 
	property_class TEXT, 
	property_class_desc TEXT, 
	property_class_previous TEXT, 
	use_code TEXT, 
	use_code_desc TEXT, 
	tax_status TEXT, 
	tax_status_description TEXT, 
	tax_status_previous TEXT, 
	total_square_footage FLOAT(53), 
	total_acreage FLOAT(53), 
	frontage FLOAT(53), 
	depth FLOAT(53), 
	homestead_pre BIGINT, 
	nez TEXT, 
	is_improved BIGINT, 
	num_bldgs BIGINT, 
	total_floor_area FLOAT(53), 
	style TEXT, 
	year_built FLOAT(53), 
	sale_price BIGINT, 
	sale_date TIMESTAMP WITH TIME ZONE, 
	assessed_value BIGINT, 
	assessed_value_previous BIGINT, 
	taxable_value BIGINT, 
	taxable_value_previous BIGINT, 
	economic_condition_factor_neigh TEXT, 
	landmap TEXT, 
	related TEXT, 
	zoning TEXT, 
	historic_designation TEXT, 
	subdivision TEXT, 
	legal_description TEXT, 
	"Shape__Area" FLOAT(53), 
	"Shape__Length" FLOAT(53), 
	geometry TEXT
)

